### PR TITLE
enables FIPS build

### PR DESCRIPTION
**Pull request by wanghaoran1988**
[SDE-1954](https://issues.redhat.com//browse/SDE-1954) This is for FedRAMP change control purposes

### CODE REVIEW

**Comment by wanghaoran1988** [comment]
It's failed because it's using golang1.13 not the boilerplate builder image, here is the fix: https://github.com/openshift/release/pull/28907

**Comment by 2uasimojo** [comment]
:eyes:

**Comment by 2uasimojo** [comment]
(Note that this repo still hasn't been properly onboarded to use standardized release config -- see https://issues.redhat.com/browse/OSD-5653.)

**Pull request merged**
